version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    restart: 'unless-stopped'
    networks:
      - backend

  certbot:
    image: certbot/certbot:arm64v8-latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw 
      - ./certbot/conf/:/etc/letsencrypt/:rw
  
  server:
    build:
      context: server
      target: production-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./certbot/conf/:/etc/ssl/:ro
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - pg-prod
    depends_on:
      - pg-prod

  pg-prod:
    image: arm64v8/postgres
    container_name: pg-prod
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: prod
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
    env_file:
      - .env
    volumes:
      - pg-prod-data:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    networks:
      - backend

  upload:
    build:
      context: upload
      target: production-build-stage
      dockerfile: Dockerfile
    container_name: upload
    ports:
      - '4000:4000'
    volumes:
      - ./upload:/app
      - /app/node_modules
      - ./certbot/conf/:/etc/ssl/:ro
    restart: 'unless-stopped'
    networks:
      - backend

  client:
    build:
      context: client
      target: production-build-stage
      dockerfile: Dockerfile
    container_name: client
    ports:
      - '8000:8000'
    volumes:
      - ./client:/app
      - /app/node_modules
      - ./certbot/conf/:/etc/ssl/:ro
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
  pg-data:
    driver: local
  pg-prod-data:
    driver: local
