import React from 'react';
import { NavBar } from '@/components/NavBar';

export function Dashboard({ }: any) {
  return (
    <div className="ml-24 text-zinc-300">
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sollicitudin lacus sit amet nisi semper viverra. Morbi cursus mi lectus, vitae feugiat leo tempus vitae. Sed fringilla, sem eget placerat suscipit, est turpis eleifend lorem, in congue erat nulla id leo. Duis metus risus, varius sed nibh eget, dapibus semper mauris. Aliquam ac diam et lacus laoreet efficitur ac vitae erat. Vivamus finibus elementum dignissim. Quisque mollis blandit luctus.

        Mauris vulputate, urna ac aliquam venenatis, dui elit suscipit tortor, id molestie arcu quam ornare ipsum. Suspendisse pharetra suscipit ante in luctus. Sed iaculis ipsum et sapien tristique tempor. Aliquam lectus nibh, pharetra non metus sed, tristique iaculis urna. Mauris in nunc mi. Curabitur vehicula felis at arcu faucibus condimentum. Duis lobortis urna ac feugiat vehicula. Aliquam id nulla at nisi vestibulum lobortis vitae et leo. Pellentesque sollicitudin mauris id tortor commodo tempus. Vestibulum finibus erat ipsum, nec cursus est consequat at. Aliquam quis diam vitae urna pulvinar ultrices at in risus. Praesent elit magna, rhoncus sed ullamcorper eu, venenatis et ante. Pellentesque sagittis quam quis ipsum convallis facilisis. Etiam a odio placerat, laoreet risus at, convallis felis. Duis orci sapien, finibus eget ex a, sollicitudin iaculis mauris.

        In non ipsum bibendum est imperdiet viverra vel quis felis. Duis venenatis lorem sed neque molestie suscipit. Nullam posuere lacus sit amet velit luctus, vitae pharetra ex porta. Donec cursus urna a leo rhoncus, eget lobortis ipsum rhoncus. Proin purus ante, sodales id venenatis ac, tempus vulputate odio. Proin posuere ullamcorper eros, sit amet dictum lectus rutrum quis. Aenean mollis, mi ut tempus mattis, metus tortor posuere enim, sed placerat risus tellus a nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras blandit aliquet sapien, vitae malesuada magna.

        Curabitur a tristique est. Sed ut ipsum euismod, hendrerit metus eget, semper ipsum. Nunc a nunc eget dolor tempus iaculis. Nullam at leo sapien. In eu lobortis mi, laoreet tempor metus. Nam ornare, leo ut posuere vehicula, neque lacus gravida tortor, nec malesuada dui justo id diam. Cras scelerisque tincidunt pulvinar. Nulla quis risus quis est finibus hendrerit. Aliquam et odio magna. Donec ullamcorper ipsum vel mauris consectetur accumsan. Integer ut lacinia ex, at fringilla urna. Aenean sed libero tellus. Maecenas vel dictum justo. Mauris ullamcorper enim vitae faucibus tincidunt. Nunc quis bibendum mauris, quis aliquam mauris.

        Nulla pretium nulla quam, a sollicitudin purus fermentum id. Nunc aliquam sit amet risus ut gravida. Mauris vel felis cursus, dictum est ac, egestas lectus. Donec id risus neque. Phasellus mattis dictum tellus vel accumsan. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tincidunt congue euismod. Aenean viverra facilisis mi nec maximus. Quisque lectus ipsum, tempor in elit vitae, ornare pharetra lorem. Phasellus facilisis velit est, sed malesuada nisi aliquam vitae. Vivamus ultrices mattis arcu, a ultrices turpis pharetra nec. Curabitur purus erat, varius ut convallis id, varius a tortor. Vivamus vehicula tortor aliquet finibus egestas. Proin malesuada et lectus nec laoreet.


        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sollicitudin lacus sit amet nisi semper viverra. Morbi cursus mi lectus, vitae feugiat leo tempus vitae. Sed fringilla, sem eget placerat suscipit, est turpis eleifend lorem, in congue erat nulla id leo. Duis metus risus, varius sed nibh eget, dapibus semper mauris. Aliquam ac diam et lacus laoreet efficitur ac vitae erat. Vivamus finibus elementum dignissim. Quisque mollis blandit luctus.

        Mauris vulputate, urna ac aliquam venenatis, dui elit suscipit tortor, id molestie arcu quam ornare ipsum. Suspendisse pharetra suscipit ante in luctus. Sed iaculis ipsum et sapien tristique tempor. Aliquam lectus nibh, pharetra non metus sed, tristique iaculis urna. Mauris in nunc mi. Curabitur vehicula felis at arcu faucibus condimentum. Duis lobortis urna ac feugiat vehicula. Aliquam id nulla at nisi vestibulum lobortis vitae et leo. Pellentesque sollicitudin mauris id tortor commodo tempus. Vestibulum finibus erat ipsum, nec cursus est consequat at. Aliquam quis diam vitae urna pulvinar ultrices at in risus. Praesent elit magna, rhoncus sed ullamcorper eu, venenatis et ante. Pellentesque sagittis quam quis ipsum convallis facilisis. Etiam a odio placerat, laoreet risus at, convallis felis. Duis orci sapien, finibus eget ex a, sollicitudin iaculis mauris.

        In non ipsum bibendum est imperdiet viverra vel quis felis. Duis venenatis lorem sed neque molestie suscipit. Nullam posuere lacus sit amet velit luctus, vitae pharetra ex porta. Donec cursus urna a leo rhoncus, eget lobortis ipsum rhoncus. Proin purus ante, sodales id venenatis ac, tempus vulputate odio. Proin posuere ullamcorper eros, sit amet dictum lectus rutrum quis. Aenean mollis, mi ut tempus mattis, metus tortor posuere enim, sed placerat risus tellus a nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras blandit aliquet sapien, vitae malesuada magna.

        Curabitur a tristique est. Sed ut ipsum euismod, hendrerit metus eget, semper ipsum. Nunc a nunc eget dolor tempus iaculis. Nullam at leo sapien. In eu lobortis mi, laoreet tempor metus. Nam ornare, leo ut posuere vehicula, neque lacus gravida tortor, nec malesuada dui justo id diam. Cras scelerisque tincidunt pulvinar. Nulla quis risus quis est finibus hendrerit. Aliquam et odio magna. Donec ullamcorper ipsum vel mauris consectetur accumsan. Integer ut lacinia ex, at fringilla urna. Aenean sed libero tellus. Maecenas vel dictum justo. Mauris ullamcorper enim vitae faucibus tincidunt. Nunc quis bibendum mauris, quis aliquam mauris.

        Nulla pretium nulla quam, a sollicitudin purus fermentum id. Nunc aliquam sit amet risus ut gravida. Mauris vel felis cursus, dictum est ac, egestas lectus. Donec id risus neque. Phasellus mattis dictum tellus vel accumsan. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tincidunt congue euismod. Aenean viverra facilisis mi nec maximus. Quisque lectus ipsum, tempor in elit vitae, ornare pharetra lorem. Phasellus facilisis velit est, sed malesuada nisi aliquam vitae. Vivamus ultrices mattis arcu, a ultrices turpis pharetra nec. Curabitur purus erat, varius ut convallis id, varius a tortor. Vivamus vehicula tortor aliquet finibus egestas. Proin malesuada et lectus nec laoreet.


        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sollicitudin lacus sit amet nisi semper viverra. Morbi cursus mi lectus, vitae feugiat leo tempus vitae. Sed fringilla, sem eget placerat suscipit, est turpis eleifend lorem, in congue erat nulla id leo. Duis metus risus, varius sed nibh eget, dapibus semper mauris. Aliquam ac diam et lacus laoreet efficitur ac vitae erat. Vivamus finibus elementum dignissim. Quisque mollis blandit luctus.

        Mauris vulputate, urna ac aliquam venenatis, dui elit suscipit tortor, id molestie arcu quam ornare ipsum. Suspendisse pharetra suscipit ante in luctus. Sed iaculis ipsum et sapien tristique tempor. Aliquam lectus nibh, pharetra non metus sed, tristique iaculis urna. Mauris in nunc mi. Curabitur vehicula felis at arcu faucibus condimentum. Duis lobortis urna ac feugiat vehicula. Aliquam id nulla at nisi vestibulum lobortis vitae et leo. Pellentesque sollicitudin mauris id tortor commodo tempus. Vestibulum finibus erat ipsum, nec cursus est consequat at. Aliquam quis diam vitae urna pulvinar ultrices at in risus. Praesent elit magna, rhoncus sed ullamcorper eu, venenatis et ante. Pellentesque sagittis quam quis ipsum convallis facilisis. Etiam a odio placerat, laoreet risus at, convallis felis. Duis orci sapien, finibus eget ex a, sollicitudin iaculis mauris.

        In non ipsum bibendum est imperdiet viverra vel quis felis. Duis venenatis lorem sed neque molestie suscipit. Nullam posuere lacus sit amet velit luctus, vitae pharetra ex porta. Donec cursus urna a leo rhoncus, eget lobortis ipsum rhoncus. Proin purus ante, sodales id venenatis ac, tempus vulputate odio. Proin posuere ullamcorper eros, sit amet dictum lectus rutrum quis. Aenean mollis, mi ut tempus mattis, metus tortor posuere enim, sed placerat risus tellus a nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras blandit aliquet sapien, vitae malesuada magna.

        Curabitur a tristique est. Sed ut ipsum euismod, hendrerit metus eget, semper ipsum. Nunc a nunc eget dolor tempus iaculis. Nullam at leo sapien. In eu lobortis mi, laoreet tempor metus. Nam ornare, leo ut posuere vehicula, neque lacus gravida tortor, nec malesuada dui justo id diam. Cras scelerisque tincidunt pulvinar. Nulla quis risus quis est finibus hendrerit. Aliquam et odio magna. Donec ullamcorper ipsum vel mauris consectetur accumsan. Integer ut lacinia ex, at fringilla urna. Aenean sed libero tellus. Maecenas vel dictum justo. Mauris ullamcorper enim vitae faucibus tincidunt. Nunc quis bibendum mauris, quis aliquam mauris.

        Nulla pretium nulla quam, a sollicitudin purus fermentum id. Nunc aliquam sit amet risus ut gravida. Mauris vel felis cursus, dictum est ac, egestas lectus. Donec id risus neque. Phasellus mattis dictum tellus vel accumsan. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tincidunt congue euismod. Aenean viverra facilisis mi nec maximus. Quisque lectus ipsum, tempor in elit vitae, ornare pharetra lorem. Phasellus facilisis velit est, sed malesuada nisi aliquam vitae. Vivamus ultrices mattis arcu, a ultrices turpis pharetra nec. Curabitur purus erat, varius ut convallis id, varius a tortor. Vivamus vehicula tortor aliquet finibus egestas. Proin malesuada et lectus nec laoreet.


        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sollicitudin lacus sit amet nisi semper viverra. Morbi cursus mi lectus, vitae feugiat leo tempus vitae. Sed fringilla, sem eget placerat suscipit, est turpis eleifend lorem, in congue erat nulla id leo. Duis metus risus, varius sed nibh eget, dapibus semper mauris. Aliquam ac diam et lacus laoreet efficitur ac vitae erat. Vivamus finibus elementum dignissim. Quisque mollis blandit luctus.

        Mauris vulputate, urna ac aliquam venenatis, dui elit suscipit tortor, id molestie arcu quam ornare ipsum. Suspendisse pharetra suscipit ante in luctus. Sed iaculis ipsum et sapien tristique tempor. Aliquam lectus nibh, pharetra non metus sed, tristique iaculis urna. Mauris in nunc mi. Curabitur vehicula felis at arcu faucibus condimentum. Duis lobortis urna ac feugiat vehicula. Aliquam id nulla at nisi vestibulum lobortis vitae et leo. Pellentesque sollicitudin mauris id tortor commodo tempus. Vestibulum finibus erat ipsum, nec cursus est consequat at. Aliquam quis diam vitae urna pulvinar ultrices at in risus. Praesent elit magna, rhoncus sed ullamcorper eu, venenatis et ante. Pellentesque sagittis quam quis ipsum convallis facilisis. Etiam a odio placerat, laoreet risus at, convallis felis. Duis orci sapien, finibus eget ex a, sollicitudin iaculis mauris.

        In non ipsum bibendum est imperdiet viverra vel quis felis. Duis venenatis lorem sed neque molestie suscipit. Nullam posuere lacus sit amet velit luctus, vitae pharetra ex porta. Donec cursus urna a leo rhoncus, eget lobortis ipsum rhoncus. Proin purus ante, sodales id venenatis ac, tempus vulputate odio. Proin posuere ullamcorper eros, sit amet dictum lectus rutrum quis. Aenean mollis, mi ut tempus mattis, metus tortor posuere enim, sed placerat risus tellus a nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras blandit aliquet sapien, vitae malesuada magna.

        Curabitur a tristique est. Sed ut ipsum euismod, hendrerit metus eget, semper ipsum. Nunc a nunc eget dolor tempus iaculis. Nullam at leo sapien. In eu lobortis mi, laoreet tempor metus. Nam ornare, leo ut posuere vehicula, neque lacus gravida tortor, nec malesuada dui justo id diam. Cras scelerisque tincidunt pulvinar. Nulla quis risus quis est finibus hendrerit. Aliquam et odio magna. Donec ullamcorper ipsum vel mauris consectetur accumsan. Integer ut lacinia ex, at fringilla urna. Aenean sed libero tellus. Maecenas vel dictum justo. Mauris ullamcorper enim vitae faucibus tincidunt. Nunc quis bibendum mauris, quis aliquam mauris.

        Nulla pretium nulla quam, a sollicitudin purus fermentum id. Nunc aliquam sit amet risus ut gravida. Mauris vel felis cursus, dictum est ac, egestas lectus. Donec id risus neque. Phasellus mattis dictum tellus vel accumsan. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tincidunt congue euismod. Aenean viverra facilisis mi nec maximus. Quisque lectus ipsum, tempor in elit vitae, ornare pharetra lorem. Phasellus facilisis velit est, sed malesuada nisi aliquam vitae. Vivamus ultrices mattis arcu, a ultrices turpis pharetra nec. Curabitur purus erat, varius ut convallis id, varius a tortor. Vivamus vehicula tortor aliquet finibus egestas. Proin malesuada et lectus nec laoreet.

        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sollicitudin lacus sit amet nisi semper viverra. Morbi cursus mi lectus, vitae feugiat leo tempus vitae. Sed fringilla, sem eget placerat suscipit, est turpis eleifend lorem, in congue erat nulla id leo. Duis metus risus, varius sed nibh eget, dapibus semper mauris. Aliquam ac diam et lacus laoreet efficitur ac vitae erat. Vivamus finibus elementum dignissim. Quisque mollis blandit luctus.

        Mauris vulputate, urna ac aliquam venenatis, dui elit suscipit tortor, id molestie arcu quam ornare ipsum. Suspendisse pharetra suscipit ante in luctus. Sed iaculis ipsum et sapien tristique tempor. Aliquam lectus nibh, pharetra non metus sed, tristique iaculis urna. Mauris in nunc mi. Curabitur vehicula felis at arcu faucibus condimentum. Duis lobortis urna ac feugiat vehicula. Aliquam id nulla at nisi vestibulum lobortis vitae et leo. Pellentesque sollicitudin mauris id tortor commodo tempus. Vestibulum finibus erat ipsum, nec cursus est consequat at. Aliquam quis diam vitae urna pulvinar ultrices at in risus. Praesent elit magna, rhoncus sed ullamcorper eu, venenatis et ante. Pellentesque sagittis quam quis ipsum convallis facilisis. Etiam a odio placerat, laoreet risus at, convallis felis. Duis orci sapien, finibus eget ex a, sollicitudin iaculis mauris.

        In non ipsum bibendum est imperdiet viverra vel quis felis. Duis venenatis lorem sed neque molestie suscipit. Nullam posuere lacus sit amet velit luctus, vitae pharetra ex porta. Donec cursus urna a leo rhoncus, eget lobortis ipsum rhoncus. Proin purus ante, sodales id venenatis ac, tempus vulputate odio. Proin posuere ullamcorper eros, sit amet dictum lectus rutrum quis. Aenean mollis, mi ut tempus mattis, metus tortor posuere enim, sed placerat risus tellus a nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras blandit aliquet sapien, vitae malesuada magna.

        Curabitur a tristique est. Sed ut ipsum euismod, hendrerit metus eget, semper ipsum. Nunc a nunc eget dolor tempus iaculis. Nullam at leo sapien. In eu lobortis mi, laoreet tempor metus. Nam ornare, leo ut posuere vehicula, neque lacus gravida tortor, nec malesuada dui justo id diam. Cras scelerisque tincidunt pulvinar. Nulla quis risus quis est finibus hendrerit. Aliquam et odio magna. Donec ullamcorper ipsum vel mauris consectetur accumsan. Integer ut lacinia ex, at fringilla urna. Aenean sed libero tellus. Maecenas vel dictum justo. Mauris ullamcorper enim vitae faucibus tincidunt. Nunc quis bibendum mauris, quis aliquam mauris.

        Nulla pretium nulla quam, a sollicitudin purus fermentum id. Nunc aliquam sit amet risus ut gravida. Mauris vel felis cursus, dictum est ac, egestas lectus. Donec id risus neque. Phasellus mattis dictum tellus vel accumsan. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tincidunt congue euismod. Aenean viverra facilisis mi nec maximus. Quisque lectus ipsum, tempor in elit vitae, ornare pharetra lorem. Phasellus facilisis velit est, sed malesuada nisi aliquam vitae. Vivamus ultrices mattis arcu, a ultrices turpis pharetra nec. Curabitur purus erat, varius ut convallis id, varius a tortor. Vivamus vehicula tortor aliquet finibus egestas. Proin malesuada et lectus nec laoreet.
      </p>
    </div>
  )
}